
[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=3600"

# Optimisation pour les fichiers statiques
[[headers]]
  for = "/cartes/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/photos/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/graphes/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"